### ISSUE TITLE
マージ方法についてのご提案

### ISSUE THREAD

**Issue by jay-es** [vuejs-jp/vite-docs-ja#100]
現在は PR 完了の際にデフォルトの `Merge pull request` でマージされていると思いますが、マージコミットや作業途中のコミットが多くなると履歴が分かりづらくなってしまうので、vuejs-jp 内の他のリポジトリや Vite 本体のやり方に合わせて `Squash and merge` でマージするのはいかがでしょうか？

ご検討よろしくお願いします。

---

もし問題ないようでしたら Settings ページの Merge button 部分にある `Allow merge commits` のチェックボックスを OFF にすると、Squash がデフォルトになるので毎回ボタンを選択する手間が省けます。

<img src="https://user-images.githubusercontent.com/46585162/116734677-857e6900-aa28-11eb-8452-fb8acd393fea.png" width="500">

**Comment by takurinton** [comment]
@jay-es 
お！！`Squash and merge` やったことありませんでした！！！次からはやろうと思います！
わざわざありがとうございます🙇‍♂️

**Comment by jay-es** [comment]
ありがとうございます！ よろしくお願いいたします:pray:

**Comment by jay-es** [comment]
@takurinton ありがとうございます！ よろしくお願いいたします:pray:
