### ISSUE TITLE
vite 公式ドキュメントの翻訳について

### ISSUE THREAD

**Issue by kazupon** [vuejs-jp/vite-docs-ja#21]
@takurinton 
先日、Vue.js 日本ユーザーグループの定例MTGで話し合ったのですが、こちら @takurinton さんが今回翻訳やりたいとのことなので、スタートしたと思うんですが、こちら @takurinton さんがリードする形でレビューやドキュメント翻訳に伴う活動の整備 (e.g. linterや formetterなど)をしていくことは可能ですか？マージ(write)権限も付与させていただきます！

もちろん、私、 @kiaking 、そしてVue.js 日本ユーザーグループも含めて、引き続き、今後支援していきます！
一人で活動するのは、忍びないのでしたら、今こちらのドキュメントを翻訳されている方といっしょにメンテしていっても大丈夫です。

**Comment by takurinton** [comment]
@kazupon さん
ありがとうございます！

> レビューやドキュメント翻訳に伴う活動の整備 (e.g. linterや formetterなど)

ここら辺についての知見がないので頼りながらになるかと思うのですが，自分で良ければぜひリードする形でやらせていただきたいです！

**Comment by kazupon** [comment]
@takurinton 
ありがとうございます！
早速ですが、今回の vite 公式日本語翻訳ドキュメント向けにチームを作りそこに invite させていただきました。
そのチームには write 権限があるので、マージ等できるはずです。
確認よろしくお願いします！

**Comment by kazupon** [comment]
/cc @nalpan
昨日の MTG で Vite 公式ドキュメントの方、興味があるということなので、nalpanさんもチームに招待しておきました。
よろしくお願いします！

**Comment by takurinton** [comment]
@kazupon ありがとうございます！JOINしました！🙇‍♂️
@nalpan さん，よろしくお願いします！

**Comment by nalpan** [comment]
@kazupon @takurinton 
JOINしました、よろしくお願いします！
活動を通してviteの理解も深めていければと思っています 💪

**Comment by kazupon** [comment]
@takurinton @nalpan 
返事が遅くなりました。
引き続き、どうぞよろしくお願いします。
何か分からないことがありましたら、vuejs-jp の slack の translation チャンネルに気軽にコメントください。:)
