### ISSUE TITLE
doc: remove unnessary word

### ISSUE THREAD

**Issue by kiaking** [vuejs-jp/vite-docs-ja#22]
New updates on head repo.
https://github.com/vitejs/vite/commit/a8b4543e4420bdeeeca8bc9141db30c6a9dd976e

**Comment by shuuji3** [comment]
こちらの変更点を確認しました。

変更内容は、"from" という単語が誤って重複して書かれていたので、片方を削除するというだけの単純な修正です。原文の意味は変わりません。

対応する日本語翻訳は、以下の1文目です。

https://github.com/vuejs-jp/vite-docs-ja/blob/f4f603952af1cec93cb964dc397abb6883773a8f/guide/index.md#L92

英文を比較しましたが、今回の変更で必要な変更はありませんでした。なので、この issue は close しても問題ありません。

close 権限がないので、どなたか close をお願いします。

**Comment by takurinton** [comment]
遅くなり申し訳ありません。
確認したところ問題なさそうなのでcloseします。
