### ISSUE TITLE
docs: static deployment guide

### ISSUE THREAD

**Issue by kiaking** [vuejs-jp/vite-docs-ja#33]
New updates on head repo.
https://github.com/vitejs/vite/commit/74e6f3d91b2b93ce4b43711930059e6fb544edb3

**Comment by jay-es** [comment]
`guide/build.md` は #8 で作業中のため、他のファイルだけ先に対応します（後続の issue で変更入っているので）

**Comment by jay-es** [comment]
`guide/build.md` も #64 にて対応しました
