### ISSUE TITLE
chore: format with prettier

### ISSUE THREAD

**Issue by kiaking** [vuejs-jp/vite-docs-ja#57]
New updates on head repo.
https://github.com/vitejs/vite/commit/5bf050948def6d9f490d413ee3bdec734e475f81

**Comment by jay-es** [comment]
差分多いが `docs/` 以外のファイルはこちらに存在しない
- guide/api-hmr.md は翻訳した時に行がずれているので直す必要あり（自分ですすみません:bow:）
- guide/assets.md は #11 で作業中
- guide/static-deploy.md は #64 で追加される

**Comment by jay-es** [comment]
こちら進めます
