### ISSUE TITLE
docs: why section convention for Vite only plugins

### ISSUE THREAD

**Issue by kiaking** [vuejs-jp/vite-docs-ja#6]
New updates on head repo.
https://github.com/vitejs/vite/commit/7f6eed98415c1ac9b76e0ad64937fd7415f03d7d

**Comment by Robjam** [comment]
@kazupon 
`docs/guide/api-plugin.md` のコンテンツとこの差分を翻訳したいと思います！
アサインいただければ良いでしょうか？

**Comment by kazupon** [comment]
@Robjam 今のところ、assgineeになる方法がコメントかisseue立てる？感じみたいなので、今のコメントで意思表示になると思うので翻訳してもいいと思います。

@takurinton 
Vuejs日本語公式ドキュメントを参考にしてガイドラインをREADMEに設定しておいた方が良さそうです。
https://github.com/vuejs/jp.vuejs.org
