### ISSUE TITLE
feat(cli): build watch mode, fix #1434

### ISSUE THREAD

**Issue by kiaking** [vuejs-jp/vite-docs-ja#68]
New updates on head repo.
https://github.com/vitejs/vite/commit/0dc6e37298e2e3efda74a1042f37bd70e3f5d3a5

**Comment by jay-es** [comment]
`guide/build.md` は #8 で作業中のため、他のファイルだけ先に対応します

**Comment by jay-es** [comment]
`guide/build.md` も #69 にて対応しました
